build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
labels:
  org.opencontainers.image.source: "https://github.com/your-user/your-repo"
