name: "iCloud Photo Downloader"
description: "Download photos from iCloud to local folder"
image: icloudpd/icloudpd:1.26.1
version: "1.0.0"
slug: "ha-icloudpd-addon"
init: false
panel_icon: "mdi:cloud-download"
panel_title: "iCloud Photo Downloader"
panel_admin: true
arch: ["armhf", "armv7", "aarch64", "amd64", "i386"],
